npm install --save^
    babel-loader^
    babel-core^
    babel-preset-es2015^
    babel-preset-react^
    babel-preset-stage-0^
    babel-polyfill^
    webpack@1.13.2^
    webpack-dev-server@1.14.1^
    style-loader^
    css-loader^
    less-loader^
    less^
    react^
    react-dom^
    redux^
    react-redux^
    reelm^
    classnames^
    immutable^
    regenerator^
    file-loader^
    git+ssh://git@git.skbkontur.ru:catalogue/retail-ui.git^
    eslint^
    eslint-config-skbkontur-retail^
    eslint-plugin-jasmine^
    jasmine
